name: Cypress Tests

on: push
jobs: 
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      -  name: Cypress run
         uses: cypress-io/github-action@v5
         with:
          spec: cypress/e2e/datadriven.cy.js
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Cypress Execution report
          path: cypress/reports/html
          retention-days: 10
